# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

dist: precise

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
env:
  - DB=MYSQL CORE_RELEASE=4.4

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=4.5
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=4.4

before_script:
  - composer self-update || true
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit tests
